## GA 프론티어 - Full training

In [2]:
import sys
sys.path.insert(0, '../')

import numpy as np
import os
import json

import pandas as pd

import glob

import plotly
import plotly.graph_objects as go
from plotly.subplots import make_subplots
plotly.offline.init_notebook_mode(connected=True)

from utils_kyy.pareto_front import identify_pareto
from utils_kyy.utils_graycode_v2 import graydecode

## [0] GA - 파레토 프론티어 찾기 (Full training)

In [3]:
data_path = '../logs/_final_New_main_full_train_GA_20200103/'

with open(os.path.join(data_path,"train_logging.log")) as json_file:
    data = json.load(json_file)

train_log = data['train_log']

In [4]:
train_log

{'0': {'epoch': 599,
  'fitness': [-91.75999764404297, 239474800.0],
  'model_id': [1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
  'time': 20645.00702738762},
 '1': {'epoch': 599,
  'fitness': [-92.38999769287109, 222941296.0],
  'model_id': [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
  'time': 21022.793867588043},
 '2': {'epoch': 599,
  'fitness': [-92.54999719238282, 329265920.0],
  'model_id': [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0],
  'time': 30918.39890384674},
 '3': {'epoch': 599,
  'fitness': [-92.22999615478516, 272711552.0],
  'model_id': [0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0],
  'time': 25826.464430332184},
 '4': {'epoch': 599,
  'fitness': [-91.63999664306641, 195924592.0],
  'model_id': [1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
  'time': 18034.645045042038},
 '5': {'epoch': 599,
  'fitness': [-92.20999846191407, 289304960.0],
  'model_id': [1, 0, 1, 1, 1, 0, 1, 0,

In [5]:
fitness = []
model_id = []
for key, val in train_log.items():
    fitness.append(val['fitness'])
    model_id.append(val['model_id'])

In [6]:
fitness

[[-92.38999769287109, 222941296.0],
 [-91.63999664306641, 195924592.0],
 [-92.20999846191407, 289304960.0],
 [-91.75999764404297, 239474800.0],
 [-92.28999768066406, 230249584.0],
 [-92.22999615478516, 272711552.0],
 [-92.48999700927735, 216172144.0],
 [-92.37999650878906, 285890432.0],
 [-92.54999719238282, 329265920.0]]

In [7]:
acc_y1 = []
flops_y2 = []
for fit_i in fitness:
    acc_y1.append(-fit_i[0])
    flops_y2.append(fit_i[1])

In [8]:
pareto_front_20gen_full_training = pd.DataFrame({'acc': acc_y1, 'flops': flops_y2})

In [9]:
pareto_front_20gen_full_training

acc        flops
0  92.389998  222941296.0
1  91.639997  195924592.0
2  92.209998  289304960.0
3  91.759998  239474800.0
4  92.289998  230249584.0
5  92.229996  272711552.0
6  92.489997  216172144.0
7  92.379997  285890432.0
8  92.549997  329265920.0

In [10]:
pareto_front_20gen_full_training_score = pareto_front_20gen_full_training.values  # (9, 2)
pareto_front_20gen_full_training_score[:, 1] = -pareto_front_20gen_full_training_score[:, 1]

In [11]:
## pareto front 찾기
full_training_score_pareto_idx = identify_pareto(pareto_front_20gen_full_training_score)
full_training_score_pareto_idx

array([1, 6, 8])

In [12]:
full_training_score_pareto = pareto_front_20gen_full_training.values[full_training_score_pareto_idx]

In [13]:
full_training_score_pareto

array([[ 9.16399966e+01, -1.95924592e+08],
       [ 9.24899970e+01, -2.16172144e+08],
       [ 9.25499972e+01, -3.29265920e+08]])

In [14]:
full_training_score_pareto[:, 1] = -full_training_score_pareto[:, 1]

In [15]:
# Plot
#  x축: FLOPS, y축: Validation accuracy
x_pareto_front_full_training = full_training_score_pareto[:, 1]
y_pareto_front_full_training = full_training_score_pareto[:, 0]

In [16]:
# Plot
# [Reference - RGB color] http://www.n2n.pe.kr/lev-1/color.htm
fig = go.Figure()

# Add traces
# fig.add_trace(go.Scatter(x=x_pareto_full_training, y=y_pareto_full_training,
#                     mode='markers',
#                     name='GA search points',
#                     marker_color='rgb(051, 102, 204)'
#                 ))

fig.add_trace(go.Scatter(x=x_pareto_front_full_training, y=y_pareto_front_full_training,
                    mode='lines+markers',
                    name='Pareto Frontier (20 gen) - Full training',
                    line_color='rgb(102, 000, 000)'  # 생상값 660000
                ))

fig.update_layout(title='Pareto Frontier',

                  xaxis_title='FLOPS',
                  yaxis_title='Validation Accuracy',
                  
                  yaxis_zeroline=False, xaxis_zeroline=False)

fig.show()

### full training 전 pareto frontier 와 비교해보기

In [17]:
data_path = '../logs/_final_New_main_experiment_1_GA_27gen/'

with open(os.path.join(data_path,"train_logging.log")) as json_file:
    data = json.load(json_file)

train_log = data['train_log']
#############################
# 총 20 generation 만 진행
#############################
# niter = len(train_log)
niter = 20

npop = len(train_log['0'])

objs_fitness = []
objs_chromo = []
gen_num = []
for i in range(niter):
    gen_num.extend([i for j in range(npop)])
    fitness_i = [train_log[str(i)][j][1] for j in range(npop)]  # [-val_acc, flops]
    chromo_i = [train_log[str(i)][j][0] for j in range(npop)]  # [-val_acc, flops]
    objs_fitness.append(fitness_i)
    objs_chromo.append(chromo_i)

objs_fitness = np.array(objs_fitness)
epoch = list(range(niter))

objs_fitness[:,:,0]= -1*objs_fitness[:,:,0]  # -val_acc => +val_acc

y1 = objs_fitness[:,:,0].reshape(-1).tolist()  # val_accuracy 는 - 붙어있는채로 사용 => minimize 하는 pareto frontier 찾는 함수 그대로 사용
y2 = objs_fitness[:,:,1].reshape(-1).tolist()
idxs = [i for i in range(len(y1))]
pareto = [0 for i in range(len(y1))]

df = pd.DataFrame({'gen':gen_num,'idx': idxs, 'acc':y1, 'flops': y2})

In [18]:
## pareto front 찾기
data_20gen_score = df[['acc','flops']].values  # df 전부

# 1) flops 에 - 붙이기 => (값이 클수록 좋은) score 로 만들기
data_20gen_score[:, 1] = -data_20gen_score[:, 1]

# 2) 파레토 프론티어 찾기
pareto_20gen_idx = identify_pareto(data_20gen_score)
pareto_front_20gen = data_20gen_score[pareto_20gen_idx]

# 파레토 프론티어 찾은 뒤, FLOPS 에 - 붙였던거 다시 부호 바꾸기
data_20gen_score[:, 1] = -data_20gen_score[:, 1]
pareto_front_20gen[:, 1] = -pareto_front_20gen[:, 1]

# 3) 파레토 프론티어에 있는 크로모좀 리스트 만들기
pareto_chromos = []
for idx in list(pareto_20gen_idx):
    i = int(idx / 20)   # e.g. 33 => 1 * 20 + 13 => 1 gen 의 14번째 => objs_chromo[1][13]  ## 각각 0번째 ~ 19번째 있음
    j = idx - i*20
    temp_chromo = objs_chromo[i][j]
    pareto_chromos.append( temp_chromo )

In [19]:
# 파레토 프론티어 직선 그리기 위해 sorting
pareto_front_20gen_df = pd.DataFrame(pareto_front_20gen)
pareto_front_20gen_df.sort_values(0, inplace=True)
pareto_front_20gen_df = pareto_front_20gen_df.values

In [20]:
# Plot
#  x축: FLOPS, y축: Validation accuracy
x_all = data_20gen_score[:, 1]
y_all = data_20gen_score[:, 0]
x_pareto = pareto_front_20gen_df[:, 1]
y_pareto = pareto_front_20gen_df[:, 0]

In [21]:
# Plot
# [Reference - RGB color] http://www.n2n.pe.kr/lev-1/color.htm
fig = go.Figure()

# Add traces
fig.add_trace(go.Scatter(x=x_all, y=y_all,
                    mode='markers',
                    name='GA search points',
                    marker_color='rgb(051, 102, 204)'
                ))


fig.add_trace(go.Scatter(x=x_pareto, y=y_pareto,
                    mode='lines+markers',
                    name='Pareto Frontier - Before full training',
                    line_color='rgb(102, 000, 000)'  # 생상값 660000
                ))


fig.add_trace(go.Scatter(x=x_pareto_front_full_training, y=y_pareto_front_full_training,
                    mode='lines+markers',
                    name='Pareto Frontier - After full training',
                    line_color='rgb(102, 000, 000)'  # 생상값 660000
                ))


fig.update_layout(title='GA search history & Pareto Frontier',
                  yaxis_zeroline=False, xaxis_zeroline=False)

fig.update_layout(title='GA history & Pareto Frontier',

                  xaxis_title='FLOPS',
                  yaxis_title='Validation Accuracy',
                  
                  yaxis_zeroline=False, xaxis_zeroline=False)

fig.show()

In [22]:
data_path = '../logs/New_main_full_train/'

with open(os.path.join(data_path,"train_logging.log")) as json_file:
    data = json.load(json_file)

train_log_ = data['train_log']

fitness_ = []
model_id_ = []
for key, val in train_log_.items():
    fitness_.append(val['fitness'])
    model_id_.append(val['model_id'])
    
acc_y1_ = []
flops_y2_ = []
for fit_i_ in fitness_:
    acc_y1_.append(-fit_i_[0])
    flops_y2_.append(fit_i_[1])
    
pareto_front_20gen_full_training_ = pd.DataFrame({'acc': acc_y1_, 'flops': flops_y2_})

In [23]:
pareto_front_20gen_full_training_

acc        flops
0  10.0  222941296.0
1  10.0  195924592.0
2  10.0  289304960.0
3  10.0  239474800.0
4  10.0  230249584.0
5  10.0  272711552.0
6  10.0  216172144.0
7  10.0  285890432.0
8  10.0  329265920.0

# full training 메인 코드 확인

In [24]:
data_30gen_score.shape

NameError: name 'data_30gen_score' is not defined

In [70]:
GA_data_path = "/root/data/basic_model/logs/_final_New_main_experiment_1_GA_27gen/"

###################################
##### 2.1. GA training.log 읽어오기
###################################
with open(os.path.join(GA_data_path, "train_logging.log")) as json_file:
    data = json.load(json_file)

train_log = data['train_log']
niter = len(train_log)
npop = len(train_log['0'])

objs_fitness = []
objs_chromo = []
gen_num = []
for i in range(niter):
    gen_num.extend([i for j in range(npop)])
    fitness_i = [train_log[str(i)][j][1] for j in range(npop)]  # [-val_acc, flops]
    chromo_i = [train_log[str(i)][j][0] for j in range(npop)]  # [1, 1, 1, 0, 0, ..., 0] => chromosome 1개
    objs_fitness.append(fitness_i)
    objs_chromo.append(chromo_i)

objs_fitness = np.array(objs_fitness)
epoch = list(range(niter)) # (27, 20, 2)

objs_fitness[:,:,0]= -1*objs_fitness[:,:,0]  # -val_acc => +val_acc
print(objs_fitness.shape)

y1 = objs_fitness[:,:,0].reshape(-1).tolist()  # val_accuracy 는 - 붙어있는채로 사용 => minimize 하는 pareto frontier 찾는 함수 그대로 사용
y2 = objs_fitness[:,:,1].reshape(-1).tolist()

chromo_list = np.array(objs_chromo) #####
print(chromo_list.shape)  # (27, 20, 21)
chromo_list = chromo_list.reshape(-1, 21)
print(chromo_list.shape)  # (540, 21)
print(chromo_list[0].shape)

idxs = [i for i in range(len(y1))]
pareto = [0 for i in range(len(y1))]

df = pd.DataFrame({'gen':gen_num,'idx': idxs, 'acc':y1, 'flops': y2})

###################################
###### 2.2 pareto front 찾기
###################################
data_30gen_score = df[['acc','flops']].values[:400, :]  ########################### ~ 20 gen ####################

# 1) flops 에 - 붙이기 => score 로 만들기
data_30gen_score[:, 1] = -data_30gen_score[:, 1]

# 2) 파레토 프론티어 찾기
pareto_30gen_idx = identify_pareto(data_30gen_score)
pareto_front_30gen = data_30gen_score[pareto_30gen_idx]

# 3) 파레토 프론티어에 있는 크로모좀 리스트 만들기
pareto_chromos = []
pareto_chromos_2 = []
for idx in list(pareto_30gen_idx):
    ##### idx 가 33 이면,인덱스가 33 임 #####
    i = int(idx / 20)   # e.g. 33 => 1 * 20 + 13 => 1 gen 의 14번째 => objs_chromo[1][13]  ## 각각 0번째 ~ 19번째 있음
    j = idx - i*20
    print(idx, i, j)
    temp_chromo = objs_chromo[i][j]
    pareto_chromos.append( temp_chromo )
    
    pareto_chromos_2.append(list(chromo_list[idx]))

(27, 20, 2)
(27, 20, 21)
(540, 21)
(21,)
1 0 1
4 0 4
6 0 6
18 0 18
47 2 7
78 3 18
208 10 8
330 16 10
376 18 16


In [73]:
pareto_chromos == pareto_chromos_2

True

In [26]:
len(objs_chromo), len(objs_chromo[0]), len(objs_chromo[0][0])

(27, 20, 21)

In [27]:
pareto_30gen_idx

array([  1,   4,   6,  18,  47,  78, 208, 330, 376])

In [28]:
len(objs_chromo)

27

In [74]:
pareto_front_30gen
## => 기존의 파레토 프론티어를 찾는 여기까진 맞음

array([[ 8.75700000e+01, -2.39474800e+08],
       [ 8.73600000e+01, -2.22941296e+08],
       [ 8.83200000e+01, -3.29265920e+08],
       [ 8.82900000e+01, -2.72711552e+08],
       [ 8.89900000e+01, -3.75730304e+08],
       [ 9.00300000e+01, -5.54664704e+08],
       [ 8.96100000e+01, -5.48163072e+08],
       [ 8.93200000e+01, -4.14405248e+08],
       [ 8.95900000e+01, -4.40997760e+08]])

In [75]:
pareto_chromos

[[1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
 [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0],
 [0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0],
 [1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
 [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0],
 [1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0],
 [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
 [1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0]]

In [76]:
def graydecode(binary):
    # binary -> decimal

    binary1 = binary
    decimal, i, n = 0, 0, 0
    while (binary != 0):
        dec = binary % 10
        decimal = decimal + dec * pow(2, i)
        binary = binary // 10
        i += 1

    # Taking xor until
    # n becomes zero
    inv = 0
    while (decimal):
        inv = inv ^ decimal;
        decimal = decimal >> 1;

    return inv

def grayCode(n):
    # Decimal to binary graycode
    # Right Shift the number
    # by 1 taking xor with
    # original number
    grayval = n ^ (n >> 1)

    return int(bin(grayval)[2:])

In [33]:
## => 이 chromos 가 evaluate_v2 로 들어가서 훈련됨

individual = pareto_chromos[0]
print(ind)

graph_name = []
# if args_train.graycode:
# Decode 해줘야 !
gray_len = len(ind)//3
for i in range(3):
    # list to string
    tmp = ''
    for j in individual[gray_len*i:gray_len*(i+1)]:
        tmp += str(j)

    # sting to binary to num
    graph_name.append(graydecode(int(tmp)))

print(graph_name)

for i in graph_name:
    print(grayCode(i))

[1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1]
[83, 126, 17]
1111010
1000001
11001


## => flops 전부 확인

In [34]:
from deap import base, creator
from deap import tools


import random
from itertools import repeat
from collections import Sequence

# For evaluate function --------------------------
import glob
from easydict import EasyDict

import numpy as np

import torch
import torch.nn as nn
import torch.backends.cudnn as cudnn    # for hardware tunning (cudnn.benchmark = True)

import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

from thop import profile
from thop import clever_format

import logging

# Gray code package
from utils_kyy.utils_graycode_v2 import *

# custom package in utils_kyy
from utils_kyy.utils_graph import load_graph
from utils_kyy.models import RWNN
from utils_kyy.train_validate import train, validate, train_AMP
from utils_kyy.lr_scheduler import LRScheduler
from torchsummary import summary
# -------------------------------------------------

In [85]:
stage_pool_path = '../graph_pool' + '/' + 'New_main' + '_' + 'experiment_1' + '/'   #####
stage_pool_path_list = []
for i in range(1, 4):
    stage_pool_path_i = stage_pool_path + str(i) + '/'  # eg. [graph_pool/run_code_name/1/, ... ]
    stage_pool_path_list.append(stage_pool_path_i)

total_graph_path_list = []
for i in range(3):
    temp = glob.glob(stage_pool_path_list[i] + '*.yaml') ############# sort 해줘야
    temp.sort()
    total_graph_path_list.append( temp )

In [86]:
flops_list = []

In [88]:
total_graph_path_list

[['../graph_pool/New_main_experiment_1/1/20_BA_5.yaml',
  '../graph_pool/New_main_experiment_1/1/20_BA_8.yaml',
  '../graph_pool/New_main_experiment_1/1/20_ER_035.yaml',
  '../graph_pool/New_main_experiment_1/1/20_ER_063.yaml',
  '../graph_pool/New_main_experiment_1/1/20_ER_074.yaml',
  '../graph_pool/New_main_experiment_1/1/20_WS_5_033.yaml',
  '../graph_pool/New_main_experiment_1/1/20_WS_9_054.yaml',
  '../graph_pool/New_main_experiment_1/1/21_BA_6.yaml',
  '../graph_pool/New_main_experiment_1/1/21_BA_7.yaml',
  '../graph_pool/New_main_experiment_1/1/21_ER_045.yaml',
  '../graph_pool/New_main_experiment_1/1/21_ER_057.yaml',
  '../graph_pool/New_main_experiment_1/1/21_ER_077.yaml',
  '../graph_pool/New_main_experiment_1/1/21_WS_11_029.yaml',
  '../graph_pool/New_main_experiment_1/1/22_BA_6.yaml',
  '../graph_pool/New_main_experiment_1/1/22_BA_8.yaml',
  '../graph_pool/New_main_experiment_1/1/22_ER_087.yaml',
  '../graph_pool/New_main_experiment_1/1/22_WS_4_062.yaml',
  '../graph_pool/

In [89]:
## => 이 chromos 가 evaluate_v2 로 들어가서 훈련됨

for individual in pareto_chromos:
    print(individual)

    graph_name = []
    # if args_train.graycode:
    # Decode 해줘야 !
    gray_len = len(individual)//3
    for i in range(3):
        # list to string
        tmp = ''
        for j in individual[gray_len*i:gray_len*(i+1)]:
            tmp += str(j)

        # sting to binary to num
        graph_name.append(graydecode(int(tmp)))

    stage_1_graph = load_graph( total_graph_path_list[0][graph_name[0]] )
    stage_2_graph = load_graph( total_graph_path_list[1][graph_name[1]] )
    stage_3_graph = load_graph( total_graph_path_list[2][graph_name[2]] )

    graphs = EasyDict({'stage_1': stage_1_graph,
                       'stage_2': stage_2_graph,
                       'stage_3': stage_3_graph
                      })

    # 2) build RWNN
    NN_model = RWNN(net_type='small', graphs=graphs, channels=78, num_classes=10, input_channel=3)
    NN_model.cuda()

    ###########################
    # Flops 계산 - [Debug] nn.DataParallele (for multi-gpu) 적용 전에 확인.
    ###########################
    input_flops = torch.randn(1, 3, 32, 32).cuda()
    flops, params = profile(NN_model, inputs=(input_flops, ), verbose=False)

    flops_list.append(flops)

[1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1]
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0]
[1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0]
[0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0]
[1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0]
[1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0]
[1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0]


In [90]:
flops_list

[316506368.0,
 332675456.0,
 264624496.0,
 242215408.0,
 325846400.0,
 301325696.0,
 304740224.0,
 325846400.0,
 329260928.0]

In [43]:
# => [1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0]
#    => 갑자기 어떻게 flops 19... 짜리 신경망이 튀어나온거지? 어디서?

# => pareto_front_30gen 에서의 flops 와 
#     => 해당 크로모좀을 구해서 신경망으로 변환 후 flops 구한 것과 flops 가 다름

# => 파레토 프론티어의 크로모좀을 구하는 것에서 에러가 있었던 듯
